// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PodPresetListerExpansion allows custom methods to be added to
// PodPresetLister.
type PodPresetListerExpansion interface{}

// PodPresetNamespaceListerExpansion allows custom methods to be added to
// PodPresetNamespaceLister.
type PodPresetNamespaceListerExpansion interface{}

// PodPresetBindingListerExpansion allows custom methods to be added to
// PodPresetBindingLister.
type PodPresetBindingListerExpansion interface{}

// PodPresetBindingNamespaceListerExpansion allows custom methods to be added to
// PodPresetBindingNamespaceLister.
type PodPresetBindingNamespaceListerExpansion interface{}
