// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/jpeeler/podpreset-crd/pkg/apis/settings/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PodPresetBindingLister helps list PodPresetBindings.
type PodPresetBindingLister interface {
	// List lists all PodPresetBindings in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.PodPresetBinding, err error)
	// PodPresetBindings returns an object that can list and get PodPresetBindings.
	PodPresetBindings(namespace string) PodPresetBindingNamespaceLister
	PodPresetBindingListerExpansion
}

// podPresetBindingLister implements the PodPresetBindingLister interface.
type podPresetBindingLister struct {
	indexer cache.Indexer
}

// NewPodPresetBindingLister returns a new PodPresetBindingLister.
func NewPodPresetBindingLister(indexer cache.Indexer) PodPresetBindingLister {
	return &podPresetBindingLister{indexer: indexer}
}

// List lists all PodPresetBindings in the indexer.
func (s *podPresetBindingLister) List(selector labels.Selector) (ret []*v1alpha1.PodPresetBinding, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PodPresetBinding))
	})
	return ret, err
}

// PodPresetBindings returns an object that can list and get PodPresetBindings.
func (s *podPresetBindingLister) PodPresetBindings(namespace string) PodPresetBindingNamespaceLister {
	return podPresetBindingNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// PodPresetBindingNamespaceLister helps list and get PodPresetBindings.
type PodPresetBindingNamespaceLister interface {
	// List lists all PodPresetBindings in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.PodPresetBinding, err error)
	// Get retrieves the PodPresetBinding from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.PodPresetBinding, error)
	PodPresetBindingNamespaceListerExpansion
}

// podPresetBindingNamespaceLister implements the PodPresetBindingNamespaceLister
// interface.
type podPresetBindingNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all PodPresetBindings in the indexer for a given namespace.
func (s podPresetBindingNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.PodPresetBinding, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PodPresetBinding))
	})
	return ret, err
}

// Get retrieves the PodPresetBinding from the indexer for a given namespace and name.
func (s podPresetBindingNamespaceLister) Get(name string) (*v1alpha1.PodPresetBinding, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("podpresetbinding"), name)
	}
	return obj.(*v1alpha1.PodPresetBinding), nil
}
