/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1alpha1

// ServiceCatalogBindingListerExpansion allows custom methods to be added to
// ServiceCatalogBindingLister.
type ServiceCatalogBindingListerExpansion interface{}

// ServiceCatalogBindingNamespaceListerExpansion allows custom methods to be added to
// ServiceCatalogBindingNamespaceLister.
type ServiceCatalogBindingNamespaceListerExpansion interface{}

// ServiceCatalogBrokerListerExpansion allows custom methods to be added to
// ServiceCatalogBrokerLister.
type ServiceCatalogBrokerListerExpansion interface{}

// ServiceCatalogInstanceListerExpansion allows custom methods to be added to
// ServiceCatalogInstanceLister.
type ServiceCatalogInstanceListerExpansion interface{}

// ServiceCatalogInstanceNamespaceListerExpansion allows custom methods to be added to
// ServiceCatalogInstanceNamespaceLister.
type ServiceCatalogInstanceNamespaceListerExpansion interface{}

// ServiceCatalogServiceClassListerExpansion allows custom methods to be added to
// ServiceCatalogServiceClassLister.
type ServiceCatalogServiceClassListerExpansion interface{}
