#!/bin/bash

VERSION=${VERSION:-}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -v|--version)
      VERSION="$2"
      shift 2
    ;;

    -*)
      error_exit "Unrecognized command line flag $1"
    ;;

    *)
      # End of arguments
      break
    ;;
  esac
done

[[ -n "${VERSION}" ]] \
  || { echo 'Please provide version'; exit 1; }

docker build -t "b.gcr.io/helm-sb-test/bookstore-nodejs:${VERSION}" . \
  && gcloud docker -- push "b.gcr.io/helm-sb-test/bookstore-nodejs:${VERSION}"
