// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	servicecatalog "github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/pkg/api/v1"
	unsafe "unsafe"
)

func init() {
	SchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_AlphaPodPresetTemplate_To_servicecatalog_AlphaPodPresetTemplate,
		Convert_servicecatalog_AlphaPodPresetTemplate_To_v1alpha1_AlphaPodPresetTemplate,
		Convert_v1alpha1_BindingCondition_To_servicecatalog_BindingCondition,
		Convert_servicecatalog_BindingCondition_To_v1alpha1_BindingCondition,
		Convert_v1alpha1_BrokerAuthInfo_To_servicecatalog_BrokerAuthInfo,
		Convert_servicecatalog_BrokerAuthInfo_To_v1alpha1_BrokerAuthInfo,
		Convert_v1alpha1_BrokerCondition_To_servicecatalog_BrokerCondition,
		Convert_servicecatalog_BrokerCondition_To_v1alpha1_BrokerCondition,
		Convert_v1alpha1_InstanceCondition_To_servicecatalog_InstanceCondition,
		Convert_servicecatalog_InstanceCondition_To_v1alpha1_InstanceCondition,
		Convert_v1alpha1_ServiceCatalogBinding_To_servicecatalog_ServiceCatalogBinding,
		Convert_servicecatalog_ServiceCatalogBinding_To_v1alpha1_ServiceCatalogBinding,
		Convert_v1alpha1_ServiceCatalogBindingList_To_servicecatalog_ServiceCatalogBindingList,
		Convert_servicecatalog_ServiceCatalogBindingList_To_v1alpha1_ServiceCatalogBindingList,
		Convert_v1alpha1_ServiceCatalogBindingSpec_To_servicecatalog_ServiceCatalogBindingSpec,
		Convert_servicecatalog_ServiceCatalogBindingSpec_To_v1alpha1_ServiceCatalogBindingSpec,
		Convert_v1alpha1_ServiceCatalogBindingStatus_To_servicecatalog_ServiceCatalogBindingStatus,
		Convert_servicecatalog_ServiceCatalogBindingStatus_To_v1alpha1_ServiceCatalogBindingStatus,
		Convert_v1alpha1_ServiceCatalogBroker_To_servicecatalog_ServiceCatalogBroker,
		Convert_servicecatalog_ServiceCatalogBroker_To_v1alpha1_ServiceCatalogBroker,
		Convert_v1alpha1_ServiceCatalogBrokerList_To_servicecatalog_ServiceCatalogBrokerList,
		Convert_servicecatalog_ServiceCatalogBrokerList_To_v1alpha1_ServiceCatalogBrokerList,
		Convert_v1alpha1_ServiceCatalogBrokerSpec_To_servicecatalog_ServiceCatalogBrokerSpec,
		Convert_servicecatalog_ServiceCatalogBrokerSpec_To_v1alpha1_ServiceCatalogBrokerSpec,
		Convert_v1alpha1_ServiceCatalogBrokerStatus_To_servicecatalog_ServiceCatalogBrokerStatus,
		Convert_servicecatalog_ServiceCatalogBrokerStatus_To_v1alpha1_ServiceCatalogBrokerStatus,
		Convert_v1alpha1_ServiceCatalogInstance_To_servicecatalog_ServiceCatalogInstance,
		Convert_servicecatalog_ServiceCatalogInstance_To_v1alpha1_ServiceCatalogInstance,
		Convert_v1alpha1_ServiceCatalogInstanceList_To_servicecatalog_ServiceCatalogInstanceList,
		Convert_servicecatalog_ServiceCatalogInstanceList_To_v1alpha1_ServiceCatalogInstanceList,
		Convert_v1alpha1_ServiceCatalogInstanceSpec_To_servicecatalog_ServiceCatalogInstanceSpec,
		Convert_servicecatalog_ServiceCatalogInstanceSpec_To_v1alpha1_ServiceCatalogInstanceSpec,
		Convert_v1alpha1_ServiceCatalogInstanceStatus_To_servicecatalog_ServiceCatalogInstanceStatus,
		Convert_servicecatalog_ServiceCatalogInstanceStatus_To_v1alpha1_ServiceCatalogInstanceStatus,
		Convert_v1alpha1_ServiceCatalogServiceClass_To_servicecatalog_ServiceCatalogServiceClass,
		Convert_servicecatalog_ServiceCatalogServiceClass_To_v1alpha1_ServiceCatalogServiceClass,
		Convert_v1alpha1_ServiceCatalogServiceClassList_To_servicecatalog_ServiceCatalogServiceClassList,
		Convert_servicecatalog_ServiceCatalogServiceClassList_To_v1alpha1_ServiceCatalogServiceClassList,
		Convert_v1alpha1_ServiceCatalogServicePlan_To_servicecatalog_ServiceCatalogServicePlan,
		Convert_servicecatalog_ServiceCatalogServicePlan_To_v1alpha1_ServiceCatalogServicePlan,
	)
}

func autoConvert_v1alpha1_AlphaPodPresetTemplate_To_servicecatalog_AlphaPodPresetTemplate(in *AlphaPodPresetTemplate, out *servicecatalog.AlphaPodPresetTemplate, s conversion.Scope) error {
	out.Name = in.Name
	out.Selector = in.Selector
	return nil
}

// Convert_v1alpha1_AlphaPodPresetTemplate_To_servicecatalog_AlphaPodPresetTemplate is an autogenerated conversion function.
func Convert_v1alpha1_AlphaPodPresetTemplate_To_servicecatalog_AlphaPodPresetTemplate(in *AlphaPodPresetTemplate, out *servicecatalog.AlphaPodPresetTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_AlphaPodPresetTemplate_To_servicecatalog_AlphaPodPresetTemplate(in, out, s)
}

func autoConvert_servicecatalog_AlphaPodPresetTemplate_To_v1alpha1_AlphaPodPresetTemplate(in *servicecatalog.AlphaPodPresetTemplate, out *AlphaPodPresetTemplate, s conversion.Scope) error {
	out.Name = in.Name
	out.Selector = in.Selector
	return nil
}

// Convert_servicecatalog_AlphaPodPresetTemplate_To_v1alpha1_AlphaPodPresetTemplate is an autogenerated conversion function.
func Convert_servicecatalog_AlphaPodPresetTemplate_To_v1alpha1_AlphaPodPresetTemplate(in *servicecatalog.AlphaPodPresetTemplate, out *AlphaPodPresetTemplate, s conversion.Scope) error {
	return autoConvert_servicecatalog_AlphaPodPresetTemplate_To_v1alpha1_AlphaPodPresetTemplate(in, out, s)
}

func autoConvert_v1alpha1_BindingCondition_To_servicecatalog_BindingCondition(in *BindingCondition, out *servicecatalog.BindingCondition, s conversion.Scope) error {
	out.Type = servicecatalog.BindingConditionType(in.Type)
	out.Status = servicecatalog.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_BindingCondition_To_servicecatalog_BindingCondition is an autogenerated conversion function.
func Convert_v1alpha1_BindingCondition_To_servicecatalog_BindingCondition(in *BindingCondition, out *servicecatalog.BindingCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_BindingCondition_To_servicecatalog_BindingCondition(in, out, s)
}

func autoConvert_servicecatalog_BindingCondition_To_v1alpha1_BindingCondition(in *servicecatalog.BindingCondition, out *BindingCondition, s conversion.Scope) error {
	out.Type = BindingConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_servicecatalog_BindingCondition_To_v1alpha1_BindingCondition is an autogenerated conversion function.
func Convert_servicecatalog_BindingCondition_To_v1alpha1_BindingCondition(in *servicecatalog.BindingCondition, out *BindingCondition, s conversion.Scope) error {
	return autoConvert_servicecatalog_BindingCondition_To_v1alpha1_BindingCondition(in, out, s)
}

func autoConvert_v1alpha1_BrokerAuthInfo_To_servicecatalog_BrokerAuthInfo(in *BrokerAuthInfo, out *servicecatalog.BrokerAuthInfo, s conversion.Scope) error {
	out.BasicAuthSecret = (*v1.ObjectReference)(unsafe.Pointer(in.BasicAuthSecret))
	return nil
}

// Convert_v1alpha1_BrokerAuthInfo_To_servicecatalog_BrokerAuthInfo is an autogenerated conversion function.
func Convert_v1alpha1_BrokerAuthInfo_To_servicecatalog_BrokerAuthInfo(in *BrokerAuthInfo, out *servicecatalog.BrokerAuthInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_BrokerAuthInfo_To_servicecatalog_BrokerAuthInfo(in, out, s)
}

func autoConvert_servicecatalog_BrokerAuthInfo_To_v1alpha1_BrokerAuthInfo(in *servicecatalog.BrokerAuthInfo, out *BrokerAuthInfo, s conversion.Scope) error {
	out.BasicAuthSecret = (*v1.ObjectReference)(unsafe.Pointer(in.BasicAuthSecret))
	return nil
}

// Convert_servicecatalog_BrokerAuthInfo_To_v1alpha1_BrokerAuthInfo is an autogenerated conversion function.
func Convert_servicecatalog_BrokerAuthInfo_To_v1alpha1_BrokerAuthInfo(in *servicecatalog.BrokerAuthInfo, out *BrokerAuthInfo, s conversion.Scope) error {
	return autoConvert_servicecatalog_BrokerAuthInfo_To_v1alpha1_BrokerAuthInfo(in, out, s)
}

func autoConvert_v1alpha1_BrokerCondition_To_servicecatalog_BrokerCondition(in *BrokerCondition, out *servicecatalog.BrokerCondition, s conversion.Scope) error {
	out.Type = servicecatalog.BrokerConditionType(in.Type)
	out.Status = servicecatalog.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_BrokerCondition_To_servicecatalog_BrokerCondition is an autogenerated conversion function.
func Convert_v1alpha1_BrokerCondition_To_servicecatalog_BrokerCondition(in *BrokerCondition, out *servicecatalog.BrokerCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_BrokerCondition_To_servicecatalog_BrokerCondition(in, out, s)
}

func autoConvert_servicecatalog_BrokerCondition_To_v1alpha1_BrokerCondition(in *servicecatalog.BrokerCondition, out *BrokerCondition, s conversion.Scope) error {
	out.Type = BrokerConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_servicecatalog_BrokerCondition_To_v1alpha1_BrokerCondition is an autogenerated conversion function.
func Convert_servicecatalog_BrokerCondition_To_v1alpha1_BrokerCondition(in *servicecatalog.BrokerCondition, out *BrokerCondition, s conversion.Scope) error {
	return autoConvert_servicecatalog_BrokerCondition_To_v1alpha1_BrokerCondition(in, out, s)
}

func autoConvert_v1alpha1_InstanceCondition_To_servicecatalog_InstanceCondition(in *InstanceCondition, out *servicecatalog.InstanceCondition, s conversion.Scope) error {
	out.Type = servicecatalog.InstanceConditionType(in.Type)
	out.Status = servicecatalog.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_InstanceCondition_To_servicecatalog_InstanceCondition is an autogenerated conversion function.
func Convert_v1alpha1_InstanceCondition_To_servicecatalog_InstanceCondition(in *InstanceCondition, out *servicecatalog.InstanceCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstanceCondition_To_servicecatalog_InstanceCondition(in, out, s)
}

func autoConvert_servicecatalog_InstanceCondition_To_v1alpha1_InstanceCondition(in *servicecatalog.InstanceCondition, out *InstanceCondition, s conversion.Scope) error {
	out.Type = InstanceConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_servicecatalog_InstanceCondition_To_v1alpha1_InstanceCondition is an autogenerated conversion function.
func Convert_servicecatalog_InstanceCondition_To_v1alpha1_InstanceCondition(in *servicecatalog.InstanceCondition, out *InstanceCondition, s conversion.Scope) error {
	return autoConvert_servicecatalog_InstanceCondition_To_v1alpha1_InstanceCondition(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogBinding_To_servicecatalog_ServiceCatalogBinding(in *ServiceCatalogBinding, out *servicecatalog.ServiceCatalogBinding, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ServiceCatalogBindingSpec_To_servicecatalog_ServiceCatalogBindingSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ServiceCatalogBindingStatus_To_servicecatalog_ServiceCatalogBindingStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ServiceCatalogBinding_To_servicecatalog_ServiceCatalogBinding is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogBinding_To_servicecatalog_ServiceCatalogBinding(in *ServiceCatalogBinding, out *servicecatalog.ServiceCatalogBinding, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogBinding_To_servicecatalog_ServiceCatalogBinding(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogBinding_To_v1alpha1_ServiceCatalogBinding(in *servicecatalog.ServiceCatalogBinding, out *ServiceCatalogBinding, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_servicecatalog_ServiceCatalogBindingSpec_To_v1alpha1_ServiceCatalogBindingSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_servicecatalog_ServiceCatalogBindingStatus_To_v1alpha1_ServiceCatalogBindingStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_servicecatalog_ServiceCatalogBinding_To_v1alpha1_ServiceCatalogBinding is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogBinding_To_v1alpha1_ServiceCatalogBinding(in *servicecatalog.ServiceCatalogBinding, out *ServiceCatalogBinding, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogBinding_To_v1alpha1_ServiceCatalogBinding(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogBindingList_To_servicecatalog_ServiceCatalogBindingList(in *ServiceCatalogBindingList, out *servicecatalog.ServiceCatalogBindingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]servicecatalog.ServiceCatalogBinding)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ServiceCatalogBindingList_To_servicecatalog_ServiceCatalogBindingList is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogBindingList_To_servicecatalog_ServiceCatalogBindingList(in *ServiceCatalogBindingList, out *servicecatalog.ServiceCatalogBindingList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogBindingList_To_servicecatalog_ServiceCatalogBindingList(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogBindingList_To_v1alpha1_ServiceCatalogBindingList(in *servicecatalog.ServiceCatalogBindingList, out *ServiceCatalogBindingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]ServiceCatalogBinding, 0)
	} else {
		out.Items = *(*[]ServiceCatalogBinding)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_servicecatalog_ServiceCatalogBindingList_To_v1alpha1_ServiceCatalogBindingList is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogBindingList_To_v1alpha1_ServiceCatalogBindingList(in *servicecatalog.ServiceCatalogBindingList, out *ServiceCatalogBindingList, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogBindingList_To_v1alpha1_ServiceCatalogBindingList(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogBindingSpec_To_servicecatalog_ServiceCatalogBindingSpec(in *ServiceCatalogBindingSpec, out *servicecatalog.ServiceCatalogBindingSpec, s conversion.Scope) error {
	out.InstanceRef = in.InstanceRef
	out.Parameters = (*runtime.RawExtension)(unsafe.Pointer(in.Parameters))
	out.SecretName = in.SecretName
	out.ExternalID = in.ExternalID
	out.AlphaPodPresetTemplate = (*servicecatalog.AlphaPodPresetTemplate)(unsafe.Pointer(in.AlphaPodPresetTemplate))
	return nil
}

// Convert_v1alpha1_ServiceCatalogBindingSpec_To_servicecatalog_ServiceCatalogBindingSpec is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogBindingSpec_To_servicecatalog_ServiceCatalogBindingSpec(in *ServiceCatalogBindingSpec, out *servicecatalog.ServiceCatalogBindingSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogBindingSpec_To_servicecatalog_ServiceCatalogBindingSpec(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogBindingSpec_To_v1alpha1_ServiceCatalogBindingSpec(in *servicecatalog.ServiceCatalogBindingSpec, out *ServiceCatalogBindingSpec, s conversion.Scope) error {
	out.InstanceRef = in.InstanceRef
	out.Parameters = (*runtime.RawExtension)(unsafe.Pointer(in.Parameters))
	out.SecretName = in.SecretName
	out.ExternalID = in.ExternalID
	out.AlphaPodPresetTemplate = (*AlphaPodPresetTemplate)(unsafe.Pointer(in.AlphaPodPresetTemplate))
	return nil
}

// Convert_servicecatalog_ServiceCatalogBindingSpec_To_v1alpha1_ServiceCatalogBindingSpec is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogBindingSpec_To_v1alpha1_ServiceCatalogBindingSpec(in *servicecatalog.ServiceCatalogBindingSpec, out *ServiceCatalogBindingSpec, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogBindingSpec_To_v1alpha1_ServiceCatalogBindingSpec(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogBindingStatus_To_servicecatalog_ServiceCatalogBindingStatus(in *ServiceCatalogBindingStatus, out *servicecatalog.ServiceCatalogBindingStatus, s conversion.Scope) error {
	out.Conditions = *(*[]servicecatalog.BindingCondition)(unsafe.Pointer(&in.Conditions))
	out.Checksum = (*string)(unsafe.Pointer(in.Checksum))
	return nil
}

// Convert_v1alpha1_ServiceCatalogBindingStatus_To_servicecatalog_ServiceCatalogBindingStatus is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogBindingStatus_To_servicecatalog_ServiceCatalogBindingStatus(in *ServiceCatalogBindingStatus, out *servicecatalog.ServiceCatalogBindingStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogBindingStatus_To_servicecatalog_ServiceCatalogBindingStatus(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogBindingStatus_To_v1alpha1_ServiceCatalogBindingStatus(in *servicecatalog.ServiceCatalogBindingStatus, out *ServiceCatalogBindingStatus, s conversion.Scope) error {
	if in.Conditions == nil {
		out.Conditions = make([]BindingCondition, 0)
	} else {
		out.Conditions = *(*[]BindingCondition)(unsafe.Pointer(&in.Conditions))
	}
	out.Checksum = (*string)(unsafe.Pointer(in.Checksum))
	return nil
}

// Convert_servicecatalog_ServiceCatalogBindingStatus_To_v1alpha1_ServiceCatalogBindingStatus is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogBindingStatus_To_v1alpha1_ServiceCatalogBindingStatus(in *servicecatalog.ServiceCatalogBindingStatus, out *ServiceCatalogBindingStatus, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogBindingStatus_To_v1alpha1_ServiceCatalogBindingStatus(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogBroker_To_servicecatalog_ServiceCatalogBroker(in *ServiceCatalogBroker, out *servicecatalog.ServiceCatalogBroker, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ServiceCatalogBrokerSpec_To_servicecatalog_ServiceCatalogBrokerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ServiceCatalogBrokerStatus_To_servicecatalog_ServiceCatalogBrokerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ServiceCatalogBroker_To_servicecatalog_ServiceCatalogBroker is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogBroker_To_servicecatalog_ServiceCatalogBroker(in *ServiceCatalogBroker, out *servicecatalog.ServiceCatalogBroker, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogBroker_To_servicecatalog_ServiceCatalogBroker(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogBroker_To_v1alpha1_ServiceCatalogBroker(in *servicecatalog.ServiceCatalogBroker, out *ServiceCatalogBroker, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_servicecatalog_ServiceCatalogBrokerSpec_To_v1alpha1_ServiceCatalogBrokerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_servicecatalog_ServiceCatalogBrokerStatus_To_v1alpha1_ServiceCatalogBrokerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_servicecatalog_ServiceCatalogBroker_To_v1alpha1_ServiceCatalogBroker is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogBroker_To_v1alpha1_ServiceCatalogBroker(in *servicecatalog.ServiceCatalogBroker, out *ServiceCatalogBroker, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogBroker_To_v1alpha1_ServiceCatalogBroker(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogBrokerList_To_servicecatalog_ServiceCatalogBrokerList(in *ServiceCatalogBrokerList, out *servicecatalog.ServiceCatalogBrokerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]servicecatalog.ServiceCatalogBroker)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ServiceCatalogBrokerList_To_servicecatalog_ServiceCatalogBrokerList is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogBrokerList_To_servicecatalog_ServiceCatalogBrokerList(in *ServiceCatalogBrokerList, out *servicecatalog.ServiceCatalogBrokerList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogBrokerList_To_servicecatalog_ServiceCatalogBrokerList(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogBrokerList_To_v1alpha1_ServiceCatalogBrokerList(in *servicecatalog.ServiceCatalogBrokerList, out *ServiceCatalogBrokerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]ServiceCatalogBroker, 0)
	} else {
		out.Items = *(*[]ServiceCatalogBroker)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_servicecatalog_ServiceCatalogBrokerList_To_v1alpha1_ServiceCatalogBrokerList is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogBrokerList_To_v1alpha1_ServiceCatalogBrokerList(in *servicecatalog.ServiceCatalogBrokerList, out *ServiceCatalogBrokerList, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogBrokerList_To_v1alpha1_ServiceCatalogBrokerList(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogBrokerSpec_To_servicecatalog_ServiceCatalogBrokerSpec(in *ServiceCatalogBrokerSpec, out *servicecatalog.ServiceCatalogBrokerSpec, s conversion.Scope) error {
	out.URL = in.URL
	out.AuthInfo = (*servicecatalog.BrokerAuthInfo)(unsafe.Pointer(in.AuthInfo))
	return nil
}

// Convert_v1alpha1_ServiceCatalogBrokerSpec_To_servicecatalog_ServiceCatalogBrokerSpec is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogBrokerSpec_To_servicecatalog_ServiceCatalogBrokerSpec(in *ServiceCatalogBrokerSpec, out *servicecatalog.ServiceCatalogBrokerSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogBrokerSpec_To_servicecatalog_ServiceCatalogBrokerSpec(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogBrokerSpec_To_v1alpha1_ServiceCatalogBrokerSpec(in *servicecatalog.ServiceCatalogBrokerSpec, out *ServiceCatalogBrokerSpec, s conversion.Scope) error {
	out.URL = in.URL
	out.AuthInfo = (*BrokerAuthInfo)(unsafe.Pointer(in.AuthInfo))
	return nil
}

// Convert_servicecatalog_ServiceCatalogBrokerSpec_To_v1alpha1_ServiceCatalogBrokerSpec is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogBrokerSpec_To_v1alpha1_ServiceCatalogBrokerSpec(in *servicecatalog.ServiceCatalogBrokerSpec, out *ServiceCatalogBrokerSpec, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogBrokerSpec_To_v1alpha1_ServiceCatalogBrokerSpec(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogBrokerStatus_To_servicecatalog_ServiceCatalogBrokerStatus(in *ServiceCatalogBrokerStatus, out *servicecatalog.ServiceCatalogBrokerStatus, s conversion.Scope) error {
	out.Conditions = *(*[]servicecatalog.BrokerCondition)(unsafe.Pointer(&in.Conditions))
	out.Checksum = (*string)(unsafe.Pointer(in.Checksum))
	return nil
}

// Convert_v1alpha1_ServiceCatalogBrokerStatus_To_servicecatalog_ServiceCatalogBrokerStatus is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogBrokerStatus_To_servicecatalog_ServiceCatalogBrokerStatus(in *ServiceCatalogBrokerStatus, out *servicecatalog.ServiceCatalogBrokerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogBrokerStatus_To_servicecatalog_ServiceCatalogBrokerStatus(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogBrokerStatus_To_v1alpha1_ServiceCatalogBrokerStatus(in *servicecatalog.ServiceCatalogBrokerStatus, out *ServiceCatalogBrokerStatus, s conversion.Scope) error {
	if in.Conditions == nil {
		out.Conditions = make([]BrokerCondition, 0)
	} else {
		out.Conditions = *(*[]BrokerCondition)(unsafe.Pointer(&in.Conditions))
	}
	out.Checksum = (*string)(unsafe.Pointer(in.Checksum))
	return nil
}

// Convert_servicecatalog_ServiceCatalogBrokerStatus_To_v1alpha1_ServiceCatalogBrokerStatus is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogBrokerStatus_To_v1alpha1_ServiceCatalogBrokerStatus(in *servicecatalog.ServiceCatalogBrokerStatus, out *ServiceCatalogBrokerStatus, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogBrokerStatus_To_v1alpha1_ServiceCatalogBrokerStatus(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogInstance_To_servicecatalog_ServiceCatalogInstance(in *ServiceCatalogInstance, out *servicecatalog.ServiceCatalogInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ServiceCatalogInstanceSpec_To_servicecatalog_ServiceCatalogInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ServiceCatalogInstanceStatus_To_servicecatalog_ServiceCatalogInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ServiceCatalogInstance_To_servicecatalog_ServiceCatalogInstance is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogInstance_To_servicecatalog_ServiceCatalogInstance(in *ServiceCatalogInstance, out *servicecatalog.ServiceCatalogInstance, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogInstance_To_servicecatalog_ServiceCatalogInstance(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogInstance_To_v1alpha1_ServiceCatalogInstance(in *servicecatalog.ServiceCatalogInstance, out *ServiceCatalogInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_servicecatalog_ServiceCatalogInstanceSpec_To_v1alpha1_ServiceCatalogInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_servicecatalog_ServiceCatalogInstanceStatus_To_v1alpha1_ServiceCatalogInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_servicecatalog_ServiceCatalogInstance_To_v1alpha1_ServiceCatalogInstance is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogInstance_To_v1alpha1_ServiceCatalogInstance(in *servicecatalog.ServiceCatalogInstance, out *ServiceCatalogInstance, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogInstance_To_v1alpha1_ServiceCatalogInstance(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogInstanceList_To_servicecatalog_ServiceCatalogInstanceList(in *ServiceCatalogInstanceList, out *servicecatalog.ServiceCatalogInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]servicecatalog.ServiceCatalogInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ServiceCatalogInstanceList_To_servicecatalog_ServiceCatalogInstanceList is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogInstanceList_To_servicecatalog_ServiceCatalogInstanceList(in *ServiceCatalogInstanceList, out *servicecatalog.ServiceCatalogInstanceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogInstanceList_To_servicecatalog_ServiceCatalogInstanceList(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogInstanceList_To_v1alpha1_ServiceCatalogInstanceList(in *servicecatalog.ServiceCatalogInstanceList, out *ServiceCatalogInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]ServiceCatalogInstance, 0)
	} else {
		out.Items = *(*[]ServiceCatalogInstance)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_servicecatalog_ServiceCatalogInstanceList_To_v1alpha1_ServiceCatalogInstanceList is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogInstanceList_To_v1alpha1_ServiceCatalogInstanceList(in *servicecatalog.ServiceCatalogInstanceList, out *ServiceCatalogInstanceList, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogInstanceList_To_v1alpha1_ServiceCatalogInstanceList(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogInstanceSpec_To_servicecatalog_ServiceCatalogInstanceSpec(in *ServiceCatalogInstanceSpec, out *servicecatalog.ServiceCatalogInstanceSpec, s conversion.Scope) error {
	out.ServiceClassName = in.ServiceClassName
	out.PlanName = in.PlanName
	out.Parameters = (*runtime.RawExtension)(unsafe.Pointer(in.Parameters))
	out.ExternalID = in.ExternalID
	return nil
}

// Convert_v1alpha1_ServiceCatalogInstanceSpec_To_servicecatalog_ServiceCatalogInstanceSpec is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogInstanceSpec_To_servicecatalog_ServiceCatalogInstanceSpec(in *ServiceCatalogInstanceSpec, out *servicecatalog.ServiceCatalogInstanceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogInstanceSpec_To_servicecatalog_ServiceCatalogInstanceSpec(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogInstanceSpec_To_v1alpha1_ServiceCatalogInstanceSpec(in *servicecatalog.ServiceCatalogInstanceSpec, out *ServiceCatalogInstanceSpec, s conversion.Scope) error {
	out.ServiceClassName = in.ServiceClassName
	out.PlanName = in.PlanName
	out.Parameters = (*runtime.RawExtension)(unsafe.Pointer(in.Parameters))
	out.ExternalID = in.ExternalID
	return nil
}

// Convert_servicecatalog_ServiceCatalogInstanceSpec_To_v1alpha1_ServiceCatalogInstanceSpec is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogInstanceSpec_To_v1alpha1_ServiceCatalogInstanceSpec(in *servicecatalog.ServiceCatalogInstanceSpec, out *ServiceCatalogInstanceSpec, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogInstanceSpec_To_v1alpha1_ServiceCatalogInstanceSpec(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogInstanceStatus_To_servicecatalog_ServiceCatalogInstanceStatus(in *ServiceCatalogInstanceStatus, out *servicecatalog.ServiceCatalogInstanceStatus, s conversion.Scope) error {
	out.Conditions = *(*[]servicecatalog.InstanceCondition)(unsafe.Pointer(&in.Conditions))
	out.AsyncOpInProgress = in.AsyncOpInProgress
	out.LastOperation = (*string)(unsafe.Pointer(in.LastOperation))
	out.DashboardURL = (*string)(unsafe.Pointer(in.DashboardURL))
	out.Checksum = (*string)(unsafe.Pointer(in.Checksum))
	return nil
}

// Convert_v1alpha1_ServiceCatalogInstanceStatus_To_servicecatalog_ServiceCatalogInstanceStatus is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogInstanceStatus_To_servicecatalog_ServiceCatalogInstanceStatus(in *ServiceCatalogInstanceStatus, out *servicecatalog.ServiceCatalogInstanceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogInstanceStatus_To_servicecatalog_ServiceCatalogInstanceStatus(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogInstanceStatus_To_v1alpha1_ServiceCatalogInstanceStatus(in *servicecatalog.ServiceCatalogInstanceStatus, out *ServiceCatalogInstanceStatus, s conversion.Scope) error {
	if in.Conditions == nil {
		out.Conditions = make([]InstanceCondition, 0)
	} else {
		out.Conditions = *(*[]InstanceCondition)(unsafe.Pointer(&in.Conditions))
	}
	out.AsyncOpInProgress = in.AsyncOpInProgress
	out.LastOperation = (*string)(unsafe.Pointer(in.LastOperation))
	out.DashboardURL = (*string)(unsafe.Pointer(in.DashboardURL))
	out.Checksum = (*string)(unsafe.Pointer(in.Checksum))
	return nil
}

// Convert_servicecatalog_ServiceCatalogInstanceStatus_To_v1alpha1_ServiceCatalogInstanceStatus is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogInstanceStatus_To_v1alpha1_ServiceCatalogInstanceStatus(in *servicecatalog.ServiceCatalogInstanceStatus, out *ServiceCatalogInstanceStatus, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogInstanceStatus_To_v1alpha1_ServiceCatalogInstanceStatus(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogServiceClass_To_servicecatalog_ServiceCatalogServiceClass(in *ServiceCatalogServiceClass, out *servicecatalog.ServiceCatalogServiceClass, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.BrokerName = in.BrokerName
	out.Description = in.Description
	out.Bindable = in.Bindable
	out.Plans = *(*[]servicecatalog.ServiceCatalogServicePlan)(unsafe.Pointer(&in.Plans))
	out.PlanUpdatable = in.PlanUpdatable
	out.ExternalID = in.ExternalID
	out.ExternalMetadata = (*runtime.RawExtension)(unsafe.Pointer(in.ExternalMetadata))
	out.AlphaTags = *(*[]string)(unsafe.Pointer(&in.AlphaTags))
	out.AlphaRequires = *(*[]string)(unsafe.Pointer(&in.AlphaRequires))
	return nil
}

// Convert_v1alpha1_ServiceCatalogServiceClass_To_servicecatalog_ServiceCatalogServiceClass is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogServiceClass_To_servicecatalog_ServiceCatalogServiceClass(in *ServiceCatalogServiceClass, out *servicecatalog.ServiceCatalogServiceClass, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogServiceClass_To_servicecatalog_ServiceCatalogServiceClass(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogServiceClass_To_v1alpha1_ServiceCatalogServiceClass(in *servicecatalog.ServiceCatalogServiceClass, out *ServiceCatalogServiceClass, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.BrokerName = in.BrokerName
	out.Description = in.Description
	out.Bindable = in.Bindable
	if in.Plans == nil {
		out.Plans = make([]ServiceCatalogServicePlan, 0)
	} else {
		out.Plans = *(*[]ServiceCatalogServicePlan)(unsafe.Pointer(&in.Plans))
	}
	out.PlanUpdatable = in.PlanUpdatable
	out.ExternalID = in.ExternalID
	out.ExternalMetadata = (*runtime.RawExtension)(unsafe.Pointer(in.ExternalMetadata))
	out.AlphaTags = *(*[]string)(unsafe.Pointer(&in.AlphaTags))
	out.AlphaRequires = *(*[]string)(unsafe.Pointer(&in.AlphaRequires))
	return nil
}

// Convert_servicecatalog_ServiceCatalogServiceClass_To_v1alpha1_ServiceCatalogServiceClass is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogServiceClass_To_v1alpha1_ServiceCatalogServiceClass(in *servicecatalog.ServiceCatalogServiceClass, out *ServiceCatalogServiceClass, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogServiceClass_To_v1alpha1_ServiceCatalogServiceClass(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogServiceClassList_To_servicecatalog_ServiceCatalogServiceClassList(in *ServiceCatalogServiceClassList, out *servicecatalog.ServiceCatalogServiceClassList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]servicecatalog.ServiceCatalogServiceClass)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ServiceCatalogServiceClassList_To_servicecatalog_ServiceCatalogServiceClassList is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogServiceClassList_To_servicecatalog_ServiceCatalogServiceClassList(in *ServiceCatalogServiceClassList, out *servicecatalog.ServiceCatalogServiceClassList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogServiceClassList_To_servicecatalog_ServiceCatalogServiceClassList(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogServiceClassList_To_v1alpha1_ServiceCatalogServiceClassList(in *servicecatalog.ServiceCatalogServiceClassList, out *ServiceCatalogServiceClassList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]ServiceCatalogServiceClass, 0)
	} else {
		out.Items = *(*[]ServiceCatalogServiceClass)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_servicecatalog_ServiceCatalogServiceClassList_To_v1alpha1_ServiceCatalogServiceClassList is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogServiceClassList_To_v1alpha1_ServiceCatalogServiceClassList(in *servicecatalog.ServiceCatalogServiceClassList, out *ServiceCatalogServiceClassList, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogServiceClassList_To_v1alpha1_ServiceCatalogServiceClassList(in, out, s)
}

func autoConvert_v1alpha1_ServiceCatalogServicePlan_To_servicecatalog_ServiceCatalogServicePlan(in *ServiceCatalogServicePlan, out *servicecatalog.ServiceCatalogServicePlan, s conversion.Scope) error {
	out.Name = in.Name
	out.ExternalID = in.ExternalID
	out.Description = in.Description
	out.Bindable = (*bool)(unsafe.Pointer(in.Bindable))
	out.Free = in.Free
	out.ExternalMetadata = (*runtime.RawExtension)(unsafe.Pointer(in.ExternalMetadata))
	out.AlphaInstanceCreateParameterSchema = (*runtime.RawExtension)(unsafe.Pointer(in.AlphaInstanceCreateParameterSchema))
	out.AlphaInstanceUpdateParameterSchema = (*runtime.RawExtension)(unsafe.Pointer(in.AlphaInstanceUpdateParameterSchema))
	out.AlphaBindingCreateParameterSchema = (*runtime.RawExtension)(unsafe.Pointer(in.AlphaBindingCreateParameterSchema))
	return nil
}

// Convert_v1alpha1_ServiceCatalogServicePlan_To_servicecatalog_ServiceCatalogServicePlan is an autogenerated conversion function.
func Convert_v1alpha1_ServiceCatalogServicePlan_To_servicecatalog_ServiceCatalogServicePlan(in *ServiceCatalogServicePlan, out *servicecatalog.ServiceCatalogServicePlan, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceCatalogServicePlan_To_servicecatalog_ServiceCatalogServicePlan(in, out, s)
}

func autoConvert_servicecatalog_ServiceCatalogServicePlan_To_v1alpha1_ServiceCatalogServicePlan(in *servicecatalog.ServiceCatalogServicePlan, out *ServiceCatalogServicePlan, s conversion.Scope) error {
	out.Name = in.Name
	out.ExternalID = in.ExternalID
	out.Description = in.Description
	out.Bindable = (*bool)(unsafe.Pointer(in.Bindable))
	out.Free = in.Free
	out.ExternalMetadata = (*runtime.RawExtension)(unsafe.Pointer(in.ExternalMetadata))
	out.AlphaInstanceCreateParameterSchema = (*runtime.RawExtension)(unsafe.Pointer(in.AlphaInstanceCreateParameterSchema))
	out.AlphaInstanceUpdateParameterSchema = (*runtime.RawExtension)(unsafe.Pointer(in.AlphaInstanceUpdateParameterSchema))
	out.AlphaBindingCreateParameterSchema = (*runtime.RawExtension)(unsafe.Pointer(in.AlphaBindingCreateParameterSchema))
	return nil
}

// Convert_servicecatalog_ServiceCatalogServicePlan_To_v1alpha1_ServiceCatalogServicePlan is an autogenerated conversion function.
func Convert_servicecatalog_ServiceCatalogServicePlan_To_v1alpha1_ServiceCatalogServicePlan(in *servicecatalog.ServiceCatalogServicePlan, out *ServiceCatalogServicePlan, s conversion.Scope) error {
	return autoConvert_servicecatalog_ServiceCatalogServicePlan_To_v1alpha1_ServiceCatalogServicePlan(in, out, s)
}
