/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen with arguments: --go-header-file=vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.go.txt --input-dirs=[github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog,github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1alpha1] --output-package=github.com/kubernetes-incubator/service-catalog/pkg/client/listers

package v1alpha1

import (
	servicecatalog "github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog"
	v1alpha1 "github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1alpha1"
	"k8s.io/kubernetes/pkg/api/errors"
	"k8s.io/kubernetes/pkg/client/cache"
	"k8s.io/kubernetes/pkg/labels"
)

// ServiceClassLister helps list ServiceClasses.
type ServiceClassLister interface {
	// List lists all ServiceClasses in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.ServiceClass, err error)
	// ServiceClasses returns an object that can list and get ServiceClasses.
	ServiceClasses(namespace string) ServiceClassNamespaceLister
	ServiceClassListerExpansion
}

// serviceClassLister implements the ServiceClassLister interface.
type serviceClassLister struct {
	indexer cache.Indexer
}

// NewServiceClassLister returns a new ServiceClassLister.
func NewServiceClassLister(indexer cache.Indexer) ServiceClassLister {
	return &serviceClassLister{indexer: indexer}
}

// List lists all ServiceClasses in the indexer.
func (s *serviceClassLister) List(selector labels.Selector) (ret []*v1alpha1.ServiceClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ServiceClass))
	})
	return ret, err
}

// ServiceClasses returns an object that can list and get ServiceClasses.
func (s *serviceClassLister) ServiceClasses(namespace string) ServiceClassNamespaceLister {
	return serviceClassNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ServiceClassNamespaceLister helps list and get ServiceClasses.
type ServiceClassNamespaceLister interface {
	// List lists all ServiceClasses in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.ServiceClass, err error)
	// Get retrieves the ServiceClass from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.ServiceClass, error)
	ServiceClassNamespaceListerExpansion
}

// serviceClassNamespaceLister implements the ServiceClassNamespaceLister
// interface.
type serviceClassNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ServiceClasses in the indexer for a given namespace.
func (s serviceClassNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ServiceClass, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ServiceClass))
	})
	return ret, err
}

// Get retrieves the ServiceClass from the indexer for a given namespace and name.
func (s serviceClassNamespaceLister) Get(name string) (*v1alpha1.ServiceClass, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(servicecatalog.Resource("serviceclass"), name)
	}
	return obj.(*v1alpha1.ServiceClass), nil
}
