// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/jpeeler/podpreset-crd/pkg/apis/settings/v1alpha1"
	scheme "github.com/jpeeler/podpreset-crd/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PodPresetBindingsGetter has a method to return a PodPresetBindingInterface.
// A group's client should implement this interface.
type PodPresetBindingsGetter interface {
	PodPresetBindings(namespace string) PodPresetBindingInterface
}

// PodPresetBindingInterface has methods to work with PodPresetBinding resources.
type PodPresetBindingInterface interface {
	Create(*v1alpha1.PodPresetBinding) (*v1alpha1.PodPresetBinding, error)
	Update(*v1alpha1.PodPresetBinding) (*v1alpha1.PodPresetBinding, error)
	UpdateStatus(*v1alpha1.PodPresetBinding) (*v1alpha1.PodPresetBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PodPresetBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.PodPresetBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PodPresetBinding, err error)
	PodPresetBindingExpansion
}

// podPresetBindings implements PodPresetBindingInterface
type podPresetBindings struct {
	client rest.Interface
	ns     string
}

// newPodPresetBindings returns a PodPresetBindings
func newPodPresetBindings(c *SettingsV1alpha1Client, namespace string) *podPresetBindings {
	return &podPresetBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the podPresetBinding, and returns the corresponding podPresetBinding object, and an error if there is any.
func (c *podPresetBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.PodPresetBinding, err error) {
	result = &v1alpha1.PodPresetBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podpresetbindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PodPresetBindings that match those selectors.
func (c *podPresetBindings) List(opts v1.ListOptions) (result *v1alpha1.PodPresetBindingList, err error) {
	result = &v1alpha1.PodPresetBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podpresetbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested podPresetBindings.
func (c *podPresetBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("podpresetbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a podPresetBinding and creates it.  Returns the server's representation of the podPresetBinding, and an error, if there is any.
func (c *podPresetBindings) Create(podPresetBinding *v1alpha1.PodPresetBinding) (result *v1alpha1.PodPresetBinding, err error) {
	result = &v1alpha1.PodPresetBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("podpresetbindings").
		Body(podPresetBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a podPresetBinding and updates it. Returns the server's representation of the podPresetBinding, and an error, if there is any.
func (c *podPresetBindings) Update(podPresetBinding *v1alpha1.PodPresetBinding) (result *v1alpha1.PodPresetBinding, err error) {
	result = &v1alpha1.PodPresetBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podpresetbindings").
		Name(podPresetBinding.Name).
		Body(podPresetBinding).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *podPresetBindings) UpdateStatus(podPresetBinding *v1alpha1.PodPresetBinding) (result *v1alpha1.PodPresetBinding, err error) {
	result = &v1alpha1.PodPresetBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podpresetbindings").
		Name(podPresetBinding.Name).
		SubResource("status").
		Body(podPresetBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the podPresetBinding and deletes it. Returns an error if one occurs.
func (c *podPresetBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podpresetbindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *podPresetBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podpresetbindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched podPresetBinding.
func (c *podPresetBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PodPresetBinding, err error) {
	result = &v1alpha1.PodPresetBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("podpresetbindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
