/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package internalversion

import (
	servicecatalog "github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog"
	"k8s.io/apimachinery/pkg/api/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterIDLister helps list ClusterIDs.
type ClusterIDLister interface {
	// List lists all ClusterIDs in the indexer.
	List(selector labels.Selector) (ret []*servicecatalog.ClusterID, err error)
	// Get retrieves the ClusterID from the index for a given name.
	Get(name string) (*servicecatalog.ClusterID, error)
	ClusterIDListerExpansion
}

// clusterIDLister implements the ClusterIDLister interface.
type clusterIDLister struct {
	indexer cache.Indexer
}

// NewClusterIDLister returns a new ClusterIDLister.
func NewClusterIDLister(indexer cache.Indexer) ClusterIDLister {
	return &clusterIDLister{indexer: indexer}
}

// List lists all ClusterIDs in the indexer.
func (s *clusterIDLister) List(selector labels.Selector) (ret []*servicecatalog.ClusterID, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*servicecatalog.ClusterID))
	})
	return ret, err
}

// Get retrieves the ClusterID from the index for a given name.
func (s *clusterIDLister) Get(name string) (*servicecatalog.ClusterID, error) {
	key := &servicecatalog.ClusterID{ObjectMeta: v1.ObjectMeta{Name: name}}
	obj, exists, err := s.indexer.Get(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(servicecatalog.Resource("clusterid"), name)
	}
	return obj.(*servicecatalog.ClusterID), nil
}
