/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package internalversion

import (
	servicecatalog "github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog"
	"k8s.io/apimachinery/pkg/api/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ServiceCatalogServiceClassLister helps list ServiceCatalogServiceClasses.
type ServiceCatalogServiceClassLister interface {
	// List lists all ServiceCatalogServiceClasses in the indexer.
	List(selector labels.Selector) (ret []*servicecatalog.ServiceCatalogServiceClass, err error)
	// Get retrieves the ServiceCatalogServiceClass from the index for a given name.
	Get(name string) (*servicecatalog.ServiceCatalogServiceClass, error)
	ServiceCatalogServiceClassListerExpansion
}

// serviceCatalogServiceClassLister implements the ServiceCatalogServiceClassLister interface.
type serviceCatalogServiceClassLister struct {
	indexer cache.Indexer
}

// NewServiceCatalogServiceClassLister returns a new ServiceCatalogServiceClassLister.
func NewServiceCatalogServiceClassLister(indexer cache.Indexer) ServiceCatalogServiceClassLister {
	return &serviceCatalogServiceClassLister{indexer: indexer}
}

// List lists all ServiceCatalogServiceClasses in the indexer.
func (s *serviceCatalogServiceClassLister) List(selector labels.Selector) (ret []*servicecatalog.ServiceCatalogServiceClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*servicecatalog.ServiceCatalogServiceClass))
	})
	return ret, err
}

// Get retrieves the ServiceCatalogServiceClass from the index for a given name.
func (s *serviceCatalogServiceClassLister) Get(name string) (*servicecatalog.ServiceCatalogServiceClass, error) {
	key := &servicecatalog.ServiceCatalogServiceClass{ObjectMeta: v1.ObjectMeta{Name: name}}
	obj, exists, err := s.indexer.Get(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(servicecatalog.Resource("servicecatalogserviceclass"), name)
	}
	return obj.(*servicecatalog.ServiceCatalogServiceClass), nil
}
