// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	settings_v1alpha1 "github.com/jpeeler/podpreset-crd/pkg/apis/settings/v1alpha1"
	versioned "github.com/jpeeler/podpreset-crd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jpeeler/podpreset-crd/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jpeeler/podpreset-crd/pkg/client/listers/settings/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodPresetBindingInformer provides access to a shared informer and lister for
// PodPresetBindings.
type PodPresetBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PodPresetBindingLister
}

type podPresetBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodPresetBindingInformer constructs a new informer for PodPresetBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodPresetBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodPresetBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodPresetBindingInformer constructs a new informer for PodPresetBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodPresetBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SettingsV1alpha1().PodPresetBindings(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SettingsV1alpha1().PodPresetBindings(namespace).Watch(options)
			},
		},
		&settings_v1alpha1.PodPresetBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *podPresetBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodPresetBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podPresetBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&settings_v1alpha1.PodPresetBinding{}, f.defaultInformer)
}

func (f *podPresetBindingInformer) Lister() v1alpha1.PodPresetBindingLister {
	return v1alpha1.NewPodPresetBindingLister(f.Informer().GetIndexer())
}
