apiVersion: settings.servicecatalog.k8s.io/v1alpha1
kind: PodPresetBinding
metadata:
  name: podpreset-binding
  namespace: test-ns
spec:
  bindingRef:
    name: ups-binding
    namespace: test-ns
  podPresetTemplate:
    metadata:
      name: presetbinding-added
    spec:
      selector:
        matchLabels:
          mutateWhenReady: "true"
      env:
        - name: PORT
          value: "1212"
