kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: apiserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver
        image: "{{ .Values.registry }}/apiserver:{{ if .Values.k8sApiServerVersion }}{{.Values.k8sApiServerVersion }}{{ else }}{{ default "latest" .Values.version }}{{ end }}"
        imagePullPolicy: Always
        args:
        - --storage-type
        - {{ default "etcd" .Values.storageType }}
        - -v
        - {{ default "\"10\"" .Values.verbosity }}
        {{ if eq .Values.storageType "etcd" }}- --etcd-servers {{ end }}
        {{ if eq .Values.storageType "etcd" }}- http://localhost:2379 {{ end }}
        ports:
        - containerPort: 6443
        volumeMounts:
        - name: apiserver-ssl
          mountPath: /var/run/kubernetes-service-catalog
          readOnly: true
      {{ if eq .Values.storageType "etcd" -}}
      - name: etcd
        image: {{ if .Values.etcdRepository }}{{ .Values.etcdRepository }}{{ else }}{{ "quay.io/coreos/etcd" }}{{ end }}:{{ if .Values.etcdVersion }}{{ .Values.etcdVersion }}{{ else }}{{ "latest" }}{{ end }}
      {{- end }}
      volumes:
      - name: apiserver-ssl
        secret:
          secretName: apiserver-ssl
---
kind: Service
apiVersion: v1
metadata:
  name: apiserver
spec:
{{ if .Values.debug }}
  type: LoadBalancer
{{ end }}
  selector:
    app: apiserver
  ports:
  - protocol: TCP
    port: 6443
    targetPort: 6443
